spring.application.name=mmp_prj

# --- ThymeleafViewResolver 설정 ---
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# --- 서버 및 세션 설정 ---
server.port=8080
server.servlet.session.timeout=60m

# --- DB 설정 (환경 변수 사용) ---
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=mmp
spring.datasource.password=tiger

#JPA 설정
#Oracle 쿼리를 사용하기 위한 설정
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#실행되는 쿼리문 확인
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jyeppp@gmail.com
spring.mail.password=zucbsgijljiumzyg
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true

#인터셉터
user.addPath=/dashboard
user.excludePath=/emailCheck,/pass,/register,/registerProcess,/searchPass